Repository redhataccess/pantheon, pull requests merged in 2020-09, with the labels that each got.

#396 Updated instances of 'UrlFragment' and 'Url Fragment' to 'URL Fragment'.
  pantheon-bundle/frontend/src/app/__snapshots__/product.test.tsx.snap
  pantheon-bundle/frontend/src/app/__snapshots__/productDetails.test.tsx.snap
  pantheon-bundle/frontend/src/app/product.tsx
  pantheon-bundle/frontend/src/app/productDetails.tsx
Labels: bug, tech review complete

#389 Reference module: Identifying module types
  pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/ref_identifying-module-types.adoc
Labels: tech review complete

#414 Added a pantheon2.yml file to manage the end-user documentation.
  pantheon2.yml
Labels: enhancement, tech review complete
