Repository redhataccess/pantheon, pull requests merged in 2021-01, with the labels that each got.

#450 Updates to the 'Importing modules into Pantheon' module
  pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_importing-content.adoc
  pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_importing-modules-into-pantheon.adoc
Labels: tech review complete

#464 FCCEUD-45: Create the Preparing content for publication assembly
  pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-preparing-content-for-publication.adoc
  pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_assigning-metadata-to-a-module.adoc
  pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_previewing-modules-in-pantheon.adoc
Labels: tech review complete

#499 Added three assemblies and their modules to the pantheon2.yml file.
  pantheon2.yml
Labels: enhancement

#501 Minor change to the "Configuring your repository" assembly.
  pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-configuring-repository.adoc
Labels: bug
